site_name: Documentación Sygma-Tech
theme:
  name: material

nav:
  - Inicio: 'index.md'
  - 'Dentix':
    - 'Servicio WolBox': 'wolbox.md'
  - 'autenticación': 'tecfinanzas_token.md'
  - 'Originación (Libranza)':
      - 'Descripción': 'tecfinanzas.md'
      - 'Importar Datos': 'tecfinanzas_importar.md'
      - 'Actualizar Datos': 'tecfinanzas_actualizar.md'
  - 'Originación (Grupo CTL)':
      - 'Importar Datos': 'grupoctl_importar.md'
      - 'Actualizar Datos': 'grupoctl_actualizar.md'
  - 'Consultas Deudor + Obligaciones + Recaudos':
      - 'Descripción': 'identificacion_descripcion.md'
      - 'Identificación Básica': 'identificacion_consulta.md'
      - 'Identificación Completa': 'identificacion_consulta_completo.md'
      - 'Id Recaudo': 'recaudo_consulta.md'
  - 'Consultar Deudor + Tipo Documento':
      - 'Servicio Consulta': "consulta_completo_credintegral.md"
  - 'Insertar Recaudos':
      - 'Descripción': 'descripcion_insertar_recaudos.md'
      - 'Aplicar Recaudo': 'recaudo_insertar.md'
  - 'Reversar Recaudos':
      - 'Descripción': 'descripcion_reversar_recaudos.md'
      - 'Reversar Recaudo': 'recaudo_reversar.md'
  - 'Simuladores':
      - 'Plan Simulador': 's_plan_simulador.md'
      - 'Simulador Cuota Maxima': 's_cuota_maxima.md'
      - 'Simulador Rotativo': 's_simulador_rotativo.md'
  - 'Originacion Promosumma':
      - 'Importar Datos': 'promosumma_originacion_import.md'
  - 'Originación Invictus':
      - 'Originación': 'invictus_originacion_import.md'
      - 'Notificación OTP': 'invictus_notificacion.md'
      - 'Validación OTP': 'invictus_validacion.md'
      - 'Selección Linea Credito': 'invictus_aprobacion_linea.md'
      - 'Reenviar OTP': 'invictus_reenviar_validacion.md'
  - 'Firma Digital Invictus':
      - 'Validación Firma': 'validacion_firma_digital.md'
      - 'Validación OTP': 'validacion_otp_firma_digital.md'
      - 'Reenvio OTP': 'validacion_reenvio_otp_firma.md'
  - 'Desembolso Invictus':
      - 'Validación Credito': 'invictus_desmebolso_validacion.md'
      - 'Validación OTP': 'invictus_desembolso_otp_valida.md'
      - 'Reenvio OTP': 'invictus_desembolso_reenvio_otp.md'
  - 'Municipio':
      - 'Consultar': 'consulta_municipio.md'
